jovandeginste/workout-tracker

views/partials/workout_details.html
views/workouts/workouts_edit.html
views/workouts/workouts_show.html

The filename can be a long string with no spaces, which messes with the details tabel size. Moving this to the top, seems like a reasonable compromise for now.

Show the filename at the top with the title

---

README.md
pkg/database/workouts.go
pkg/database/workouts_map.go

fix: when date is missing from metadata, use first track first segment first point's timestamp

---

pkg/app/self_handlers.go
pkg/app/templates.go
pkg/database/profile.go
pkg/database/user.go
pkg/templatehelpers/template_funcs.go
pkg/templatehelpers/template_funcs_test.go
translations/de.json
translations/messages.json
translations/nl.json
views/partials/user_profile_timezone.html
views/partials/workout_point_title.html
views/user/user_profile.html

This should remove the need to parse times client side (with javascript), and purely do this server side. This should thus make it more consistent.
This should fix #17

Use per-user timezone to show local times

---

pkg/database/workouts_map.go

This disables altitude correction for GPXes from Workoutdoors. It uses `creator="Apple Watch"` so it might mess with other apps from Apple Watch that *do* need correction (I don't know if these exist).

Do not apply altitude correction for files from Workoutdoors (Apple Watch)

---

pkg/templatehelpers/template_funcs.go
pkg/templatehelpers/template_funcs_test.go

The mm:ss format is a bit more intuitive (for me/as runner at least) than the m.f format (where f is a fraction of a minute)

fix: format tempo as mm:s (where s is seconds)

---

pkg/database/gorm.go
pkg/database/user.go
pkg/database/workouts.go

This should auto-migrate the current content, and clear the columns in the workouts table.

Move original content of GPX file to separate table

---

pkg/database/workouts_map.go

Workoutdoors generates multiple segments in a track (`<trkseg>`) when pausing along the way. 
This change ensures all segments are included and counts the time passed between segments as pause time.

fix: deal correctly with GPX files that have multiple segments and count time between segments as pause time

---

views/partials/workout_breakdown.html
views/partials/workout_details.html
views/partials/workout_item.html
views/workouts/workouts_list.html

This PR prevents statistics with units (such as `1:23 min/km`) from being wrapped over two lines. This looks much nicer imo.
Before:
After:
I applied the class `whitespace-nowrap` to all places I could find, might have missed some though.

fix: prevent number and units from being wrapped

---

pkg/database/workouts.go

When we remove a workout, we should clean up the associated GPX file; otherwise, you can not add it back later.
We also override the "NOT NULL" constraint by setting a different tag. This seems to be a weird workaround, but it's only for the time it needs to get removed entirely, anyway.
This should fix #33

Remove GPX when removing workout, and fix not null constraint

---

pkg/database/workouts.go
pkg/database/workouts_map.go
pkg/database/workouts_statistics.go
pkg/templatehelpers/template_funcs.go
views/partials/workout_breakdown.html

This will no longer crash when uploading workout files without any kind of distance. This may be useful to still get some duration out of it.
The resulting information is weird (for now) because of the many 0's.
Fixes #38

Add (kind of) support for distance-less GPX and FIT

---

Dockerfile
README.md
pkg/app/app.go
pkg/app/background.go
pkg/app/self_handlers.go
pkg/database/profile.go
pkg/database/user.go
pkg/database/workouts.go
views/user/user_profile.html

Each user can configure a folder from which to automatically import workout files. This folder is then checked every minute, and each file older than one minute is added.
When this process fails, the file is moved to the "failed" subfolder; otherwise the file is added to the "done" subfolder. The subfolders are created when needed.
Fixes #40

Add auto-import feature

---

pkg/app/data.go
views/partials/header.html
views/user/user_profile.html
views/user/user_show.html

Removed top-level `userProfileLanguage` and `userProfileTotalsShow` values in templates, making them dependent on the current user's data instead. This change reduces the number of attributes that are added at the top level.

Remove top-level user profile language and totals show from templates

---

pkg/app/api_handlers.go
pkg/app/routes.go
pkg/database/profile.go
pkg/database/user.go

When we want to use the API from the web interface (eg. to update statistics), we will authenticate using the JWT token instead of the API key. This change should allow this.

Allow API access via JWT authentication

---

views/partials/workout_details.html
views/workouts/workouts_list.html

Some places lacked the HumanDuration filter, which meant the values shown were not consistent and sometimes weird, like showing nanoseconds.
Fixes #66

Use the HumanDuration filter to properly print durations

---

pkg/app/self_handlers.go
pkg/database/profile.go
views/user/user_profile.html
views/workouts/workouts_show.html

When the setting is disabled system wide, this will take precedence over the per-user setting.
We also update the user id inside the profile struct, in case the user had no profile yet. This also fixes #61 for existing setups.

Add per-user setting to disable social sharing buttons

---

pkg/app/templates.go
pkg/database/profile.go
pkg/templatehelpers/imperial.go
pkg/templatehelpers/metric.go
pkg/templatehelpers/template_funcs.go
pkg/templatehelpers/template_funcs_test.go
views/partials/statistic_tile.html
views/partials/stats_records_distance.html
views/partials/stats_records_totals.html
views/partials/workout_breakdown.html
views/partials/workout_details.html
views/partials/workout_item.html
views/partials/workout_point_title.html
views/workouts/workouts_list.html

- Remove units from Human* functions to return only numerical value Update     s
- affected templates to include units based on CurrentUser.PreferredUnit       s
This commit refactors the Human* functions to remove the units from the returned values, and updates the affected templates to include the units based on the CurrentUser.PreferredUnits.

Update Human* functions to return values without units

---

pkg/database/workouts.go

The MapData was saved again and again to the database, as new records, upon refresh.
We now keep track of the old ID and CreatedAt values, which should update the existing record instead of creating new records.

Prevent duplicate MapData entries

---

pkg/database/workouts.go
pkg/database/workouts_map.go

This takes the first time from the first point in the GPX file as the time of the workout, instead of the timestamp from the metadata. The timestamp from the metadata is then used as fallback, but may have been altered by converters.
We also change the auto-detection algorithm, so the limit of running vs walking is now 7 instead of 5 km/h.
Fixes #57

Switch the timestamp detection in a GPX file

---

pkg/database/gorm.go
pkg/database/workouts.go
pkg/database/workouts_map.go
pkg/database/workouts_test.go

We add an uniqueIndex constraint on the WorkoutID column, to ensure it remains a 1-1 relation. Since there may already be duplicate records in the table, we need to perform a pre-migration cleanup. This may happen before the table is even created (first run), so we need to check if the table exists.
We also update our tests, since they seemed to add extra records!

Ensure the workout-mapdata relation is a 1-1 mapping

---

pkg/database/statistics.go

When calculating bucket-statistics, we show the average of averages, but here we show the max (records!).

Show the max average speed when showing records

---

pkg/database/gorm.go
pkg/database/workouts.go

This would mean the user has uploaded multiple files with the same (partial) workout, which is not what the user wants.
We also delete any current entries with the same date and user id, except the last one of each tuple.
Fixes #94

Ensure a user can not have two workouts with the same time

---

README.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/app/api_handlers.go
pkg/app/data.go
pkg/converters/tcx.go
pkg/database/workouts.go
pkg/importers/fitotrack.go
pkg/importers/importer.go
translations/de.json
translations/messages.json
translations/nl.json
views/user/user_profile.html

This adds support for FitoTrack to automatically upload workouts via HTTP POST. We had to add authentication via query parameter, since FitoTrack did not support Header or BasicAuth authentication.
We also now have a README section that can be extended.

Add support for submitting workouts via API

---

views/partials/workout_show_stats.html

We were comparing first & last points in the same graphs, which offset the lines by one minute...

Fix the graph async in the workout statistics

---

views/partials/stats_records_totals.html
views/user/user_show.html

Instead of showing the authenticated user's information, we should show the selected user's totals and records. We still use the authenticated user's preferred units.
Fixes #120

Show the totals/records for the selected user

---

pkg/database/statistics.go
views/partials/messages.html
views/partials/stats_records_totals.html
views/partials/user_profile_totals_show.html

This is per user, and still overridable in the profile settings.
Fixes #129

Automatically use most popular workout in totals

---

pkg/app/self_handlers.go

When a user has no profile yet, the creation should work correctly. We can improve the assignment of values too.
Fixes #139

Improve the creation of a user profile

---

Makefile

On macOS, calling `date` with `--rfc3339` is not supported, this PR makes it use a different incantation (that as far as I can see also works on Linux). The date it produces is in a slightly different format, not sure where this is used anyway?

fix: call date in a different way from the Makefile to fix build error on macOS

---

pkg/app/self_handlers.go
pkg/database/profile.go

Unchecking options like API access was not working, because unchecked checkboxes are not sent as form values.
This change first unsets all booleans, which may or may not be enabled again through the form.

Fix disabling options in profile settings

---

Makefile
assets/output.css
package-lock.json
package.json
pkg/app/app.go
pkg/app/routes.go
pkg/app/workouts.go
pkg/app/workouts_handlers.go
pkg/database/equipment.go
pkg/database/profile.go
pkg/database/workout_type.go
pkg/database/workouts.go
pkg/database/workouts_map.go
views/equipment/equipment_show.html
views/partials/user_profile_preferred_units.html
views/partials/workout_details.html
views/workouts/workout_form.html
views/workouts/workouts_add.html
views/workouts/workouts_show.html

Eg. add weight and repetition based workouts.
Addresses #145, #140, #134, #55

Add other types of workouts without location

---

assets/output.css
pkg/importers/fitotrack.go
pkg/importers/generic.go
pkg/importers/importer.go

This allows importing a GPX file without any further metadata. The workout type (running, walking, cycling) will then be inferred automatically, similar to uploading it through the web UI.

Add generic "import" endpoint to API

---

views/partials/workout_details.html

If a workout is not a location-based workout, don't show the location: it will always be missing, so not useful.

Don't show missing location when not location based

---

assets/output.css
pkg/database/extra_metrics.go
pkg/database/workouts.go
pkg/templatehelpers/icons.go
translations/de.json
translations/fr.json
translations/it.json
translations/messages.json
translations/nl.json
views/partials/workout_details.html

This should visualize in the details what else can be graphed.

Show what other metrics are contained in the workout

---

assets/output.css
pkg/converters/fit.go
pkg/database/extra_metrics.go
pkg/database/user_test.go
pkg/database/workouts.go
pkg/database/workouts_map.go
pkg/templatehelpers/icons.go
translations/de.json
translations/fr.json
translations/it.json
translations/messages.json
translations/nl.json
views/partials/workout_details.html
views/partials/workout_point_title.html
views/partials/workout_show_stats.html
views/workouts/workouts_show.html

This adds better support for Apple Health GPX files, and provides a standardized way to store the extra metric names.
We also parse a few extra metrics, but don't have a way to show them for now (if ever). Only a visual cue to show whether there is heading information in the GPX points.

Parse extention nodes and standardize extra metric names

---

pkg/app/background.go
pkg/database/workouts.go

There is nothing to update there (for now)...
Also generically catch any panic in the background loop and recover from it with a message.

Skip updates for non-GPX based workouts

---

assets/output.css
main.css
pkg/app/workouts.go
pkg/database/profile.go
pkg/database/workouts.go
pkg/database/workouts_map.go
pkg/database/workouts_statistics.go
pkg/templatehelpers/imperial.go
pkg/templatehelpers/metric.go
views/partials/workout_map.html
views/partials/workouts_list_details.html
views/workouts/workout_form.html
views/workouts/workouts_edit.html
views/workouts/workouts_show.html

In order to correctly support Imperial units and locales, we:
- change the input field for duration into split fields for hours,
minutes and seconds (bonus: we now allow seconds)
- correctly convert the input distance from the user's preferred unit
- for this, we add and use more constants
There's now a new reset button on the edit form that resets the input
fields back to their initial values, and a close button to go back to
the view.
We no longer show a few workout details in the list view:
- average speed without pauze
- max speed
We update the workout view page, to hide the map if there is no map to
show (even if it's a location-based workout). This is currently
determined by checking if the map center is "0, 0".
We also update the cosmetic layout of the buttons, to be more …

fix: support editing workouts using Imperial units

---

pkg/geocoder/reverse.go

The logic was inversed accidentally. This is now corrected.

fix: calculate rate limit time remaining

---

views/user/user_profile.html

By setting the button's types to "button", the `return false;` is no longer needed.

refactor: improve API button style and behavior

---

README.md

Documentation has been added to provide clear instructions on how to use the generic upload endpoint using `curl`. This includes examples for both cases where an API key is provided in the header or as a query parameter.

docs: add generic upload API endpoint usage documentation

---

pkg/database/workouts.go
views/workouts/workouts_edit.html
views/workouts/workouts_show.html

There was a key that stored the filename of a workout, which was no longer used and therefore removed in the previous PR (#232). This broke the code for viewing and editing a workout, which still referenced the old key.
We fix this by adding a function, that dynamically generates a new filename if there was none, and checking whether we have data in the views.

fix: add function to get filename of workout

---

Makefile
package-lock.json
package.json

Prettier and air were missing on my system, so `make dev` and `make build-all` would not work. This adds prettier as 'dev dependency' in package.json and adds a command to install air in the `install-deps' target of the Makefile.

fix: add prettier and air dependencies

---

Makefile

We don't need all dependencies when building the project; the Golang dependencies for development purposes are only needed then.

Split dependency installation in dev vs build

---

views/partials/workout_show_stats.html

This replaces y=0 with y=null for chart points in the series for 'heart rate'. 
Zero heart rates don't really make senes (but sometimes happen when i.e. the heart rate sensor hasn't measured anything yet). The zero points do however mess up the Y axis scale.
Before: 
After:

fix: do not show zero heart rate in chart

---

README.md

This change adds a section to the README that asks users to donate workout files for testing purposes. The section encourages users to contribute to the project by sharing their files, which will help the developers improve the accuracy and functionality of the software. The section also includes guidelines for sharing files and ensures users understand the project's usage of donated files.

feat: Add donation section to README

---

assets/output.css
pkg/app/templates.go
pkg/database/workout_met.go
pkg/database/workout_type.go
pkg/database/workouts.go
pkg/templatehelpers/icons.go
pkg/templatehelpers/template_funcs.go
views/partials/workout_details.html
views/user/user_profile.html

Adds calorie burned calculation and display on workout details page. The calories are estimated based on the activity, assuming a weight of 70 kg. This gives the user a rough idea of how many calories they burned during the workout. Also adds repetition frequency per minute display on workout details page. This is useful for understanding the intensity of a repetition-based workout.
Fixes #260

feat: Add calorie calculation and display

---

README.md

Added a link to the Matrix chatroom to the README. This allows users to get in touch with the community and ask questions or discuss the project.

docs: Add a link to the Matrix chatroom

---

.github/dependabot.yml

add dependabot to take care of dependency update.
please not forget to [active dependabot in settings of GitHub project](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide)

add dependabot to take care of dependency update

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/database/workout_met.go

this PR try to add golangci-lint so we don't merge code that not pass golangci-lint rull.
Note: *currently make test-go run golangci-lint that fails but it is not show in CI so potential merge code that not pass (that happen right now)*

add golangci-lint

---

pkg/templatehelpers/template_funcs.go

fix: show min/mi value instead of min/km when using imperial units

---

assets/common.js
assets/output.css
main.css
pkg/app/data.go
pkg/app/routes.go
pkg/app/routes_test.go
pkg/app/workouts_handlers.go
pkg/database/statistics.go
pkg/database/user.go
pkg/database/workouts.go
pkg/templatehelpers/icons.go
views/partials/alerts.html
views/partials/header.html
views/partials/version.html
views/partials/workout_actions.html

Adds a feature to share workouts publicly via a unique URL.
- A new `/share/:uuid` endpoint renders a workout based on the provided UUID.
- A `PublicUUID` field is added to the `Workout` model to store the UUID for sharing.
- The `workouts_share` endpoint generates a new public UUID for the workout.
- The UI includes a button to copy the public UUID to the clipboard, and a button to generate a new shareable link.
- Updated the `workout_actions` template to include the share functionality.
Fixes #239

feat: add workout sharing functionality

---

assets/map.js
views/partials/route_segment_map.html

When the track does not have any speed data, the elevation view is shown by default. An option has been added to the interface to manually toggle between elevation and speed view, which is used for route segments.

feat: Show elevation of route segment instead of speed

---

pkg/importers/generic.go

The type of workout is inferred from the file's extension; by adding `.gpx`, the importer knows how to parse it.
Fixes #307

fix: Use default file name "workout.gpx"

---

pkg/importers/fitotrack.go

The `Filename` field was set to an empty string, which is not needed and can be removed. This confused the importer, since it uses the filename to assess which type of file it gets
Fixes #307 (again)

fix(importer): Remove Filename field reset

---

pkg/app/api_handlers.go
pkg/app/routes.go

Pass user validation as a middleware instead of a SuccessFunc. Add redirect to signout endpoint if user is not found. Add error logging for failed user validation.
Ref: #321

feat(middleware): Validate user on all endpoints

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/app/admin_data.go
pkg/app/admin_handlers.go
pkg/app/background.go
pkg/database/config.go
pkg/database/equipment.go
pkg/database/gorm.go
pkg/database/profile.go
pkg/database/route_segments.go
pkg/database/user.go
pkg/database/workouts.go
pkg/database/workouts_map.go
pkg/database/workouts_test.go

This fixes a number of constraint issues where deletes were not cascaded etc.
A few other issues were fixed along the way.

Fix database constraints and improve data matching

---

pkg/database/gorm.go

This commit introduces pre-migration cleanup actions to ensure data integrity.
It removes map data details associated with map data IDs that have an earlier creation date, eliminating potential inconsistencies in map data details.

feat(database): Add pre-migration cleanup actions

---

views/partials/head.html

The material icons CSS file was no longer being used in the application.

Style(css): Remove unused material icons link

---

assets/output.css
views/workouts/workouts_list.html

Added a `.cursor-pointer` class to style the cursor as a pointer when hovering over elements. This improves the user experience by providing clearer visual feedback that an element is interactive. Applied this class to the filter summary in `workouts_list.html` to make it clear that the summary is clickable.

feat(style): Add cursor pointer style and apply to filter summary

---

pkg/converters/parse.go
pkg/database/gpx_sample_1_test.go
pkg/database/workouts_test.go

Some workout files don't have a name; in that case, we use the filename as the name of the workout.

refactor(converters): Improve name detection

---

pkg/converters/parse.go

The previous implementation incorrectly assumed that GPX files with tracks had names. This commit modifies the parsing logic to correctly handle such files by checking whether the first track has a name or not

Fix(gpx): Handle GPX files without track names

---

.air.toml
pkg/database/statistics.go
translations/en.yaml
views/helpers/statistics.go

This commit improves the statistics query to handle the `since` parameter more gracefully.
The query only adds a date filter if the `since` parameter is not "forever". This change ensures that the statistics are calculated correctly for all time periods. Additionally, the translation for "forever" has been added to support this new functionality. Finally, the `since` options in the UI have been updated to allow selection of "forever".

feat(database): Improve statistics query

---

pkg/database/workouts.go

The previous implementation of `UpdateAverages` could lead to a division by zero error if the workout's total duration was zero. This commit adds a check to handle this case, setting the average speed to 0 if the duration is 0, preventing the error and providing a more robust calculation. This ensures that the application remains stable even when processing workouts with zero duration.

fix(database): Handle zero duration in workout average speed calculation

---

pkg/app/workouts.go
pkg/database/workouts.go

The previous implementation used incorrect redirect URLs after creating or updating a workout. This commit updates the redirect URLs to correctly point to the "workout-add" route after creating a workout, and to the newly created workout's "workout-show" route after saving changes. This ensures users are redirected to the appropriate page after interacting with workouts. Additionally, it handles the case of saving a new workout without an ID, ensuring the `Workout.Data` is properly associated with the newly created workout.
Fixes #412

fix(app): Fix redirect URLs after workout creation

---

Makefile
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/app/api_handlers.go
pkg/app/workouts.go

Added an endpoint to create new workouts manually, using a POST request to `/workouts`. This allows users to add workouts without relying on automatic imports from external sources. The request body expects a JSON payload conforming to the `ManualWorkout` struct, providing fields such as date, time, location, distance, duration, and type of workout. The response returns a JSON object containing the newly created workout data. Error handling is included to manage invalid inputs and database errors. This significantly enhances the flexibility of the application by supporting manual data entry. The swagger documentation has also been updated to reflect this new endpoint. The `results` field in the API responses has been changed to plural.
Fixes #317

feat(api): Add endpoint to create manual workouts

---

Dockerfile

The `go build` command is improved to build all the commands in the `cmd` directory. These binaries are all added to the final image.

fix(build): Improve Docker build process

---

cmd/fitbit-sync/cli.go
cmd/fitbit-sync/commands.go
cmd/fitbit-sync/sync.go

This commit introduces more granular control over which Fitbit data is synced to the Workout Tracker. Previously, all available data (weight, height, steps, and activities) was synced by default. This update allows users to selectively enable or disable syncing for each data type using command-line flags.

feat(cli): Add granular control over Fitbit data syncing

---

translations/nb_NO.yaml

Renamed the Norwegian translation file from `no.yaml` to `nb_NO.yaml` to better reflect the language code for Norwegian Bokmål. This improves clarity and consistency with other language files, ensuring that the correct language code is used for proper language detection and selection.

Refactor(i18n): Rename Norwegian translation file

---

pkg/database/user.go

The database functions for retrieving workouts and equipment did not set the `User` field in the returned objects.
Fixes #442

fix(database): Set User in Workouts and Equipment

---

translations/de.yaml
translations/en.yaml
translations/fi.yaml
translations/nl.yaml
translations/zh_Hans.yaml

The ellipsis was rendered incorrectly as "...". This commit replaces the three dots with the ellipsis character "…" to ensure proper rendering across different platforms and character encodings. This affects the translations for German, English, Finnish, Dutch, and Simplified Chinese.

fix(i18n): Correct ellipsis in translations

---

pkg/app/routes.go

The last change created a regression, which did not use the user's choice of language as selected in the user's profile settings.
This updates the preferred language after the user is validated.

fix(i18n): Re-set the user's requested language after authentication

---

pkg/converters/fit.go

This commit fixes an issue where invalid coordinates (NaN) in FIT files would cause parsing issues.
The code now skips records with NaN latitude or longitude values, preventing the creation of invalid GPX points. This ensures that the converter can process FIT files with potentially corrupted location data.

fix(fit): skip invalid coordinates

---

pkg/database/route_segments.go
pkg/database/workouts.go

The `Content` fields in `RouteSegment` and `GPXData` schemas were defined with `gorm:"type:text"`. This change updates the type to `gorm:"type:bytes"` which is more appropriate for storing binary data like file content. This fixes issues related to character encoding and ensures data integrity when storing and retrieving file content from the database.
Specifically, this fixes storing fit files in a PostgreSQL database.

fix(db): use bytes type for content fields

---

views/helpers/language.go

Adds support for the Polish language to the application. This includes adding `language.Polish` to the list of supported languages, allowing the application to be translated into Polish and used by Polish-speaking users.

feat(i18n): add polish language support

---

views/helpers/helpers.go

This change fixes the translation keys for order by and order direction options.
fixes: #498

fix(i18n): rename translation keys to order by options

---

pkg/converters/workout.go

Missed one. 
`geo.Adress` is also still capitalized but as far as I see changing it would require some more work.

fix(api) Fix WorkoutData json names

---

pkg/app/handlers.go
views/helpers/helpers.go
views/user/statistics.templ
views/user/statistics_templ.go

This commit fixes the statistics page by using the correct keys for translations.
Fixes #516

fix(statistics): translate statistics page

---

pkg/database/measurement.go
pkg/database/user.go

This commit fixes an issue where measurements were not being saved with the
correct timezone. The `NewMeasurement` function now creates measurements using
the user's timezone. Also, the `GetCurrentMeasurement` function now retrieves
measurements using the user's timezone. This ensures that measurements are
always saved and retrieved with the correct date.
Fixes #521

fix(measurement): ensure correct measurement timezone handling

---

pkg/database/gorm.go

Add a check for column existence before attempting to update `average_speed` and `average_speed_no_pause`.
This prevents errors during database setup or migration on tables where these specific columns might not yet or no longer exist, improving the robustness of the pre-migration steps.
Fixes #542

fix(database): Prevent pre-migration error on missing columns

---

pkg/database/statistics.go
pkg/database/user_statistics.go

Introduce `RawBucket` field in the `Bucket` struct to clearly separate the aggregation period from a representative day within that period. This field now stores the actual bucket string used for grouping (e.g., '2023-W40', '2023-10').
Rename the SQL alias for the primary bucket column from `bucket` to `raw_bucket` in `GetBucketFormatExpression`. This aligns the database query output with the new `RawBucket` struct field.
Add `GetDayBucketFormatExpression` to select a `YYYY-MM-DD` formatted date as `bucket`. This ensures the `Bucket` field in the struct consistently holds a specific date, which is crucial for frontend rendering, allowing charts to plot data points with precise date values even when aggregated by week or month.
Update the `GROUP BY` clause to use the `raw_bucket` alias, …

feat(statistics): Distinguish aggregation bucket from representative day

---

pkg/database/statistics.go

When (accidentally) importing a workout with a duration of `0` or pause time equal to the total duration the dashboard and statistics break.

Fix zero division errors for workouts with total duration of 0

---

CHANGELOG.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/database/workout_type.go
translations/en.yaml
views/user/stats.templ
views/user/stats_templ.go

Handle empty workout types by returning "none" for their string representation.
This provides a clear identifier for an unselected workout type, which is then
used in UI elements.
Add 'none' and 'auto-detect' translations for sports.
Display the first statistic tile based on the user's `Profile.TotalsShow`
preference instead of the query results. This should be the same as the results
from the query, except when the query returns no results (in which case, the
value from the profile makes more sense!)

feat(stats): Allow users to customize displayed total statistics

---

pkg/app/users_handlers.go
views/workouts/show.templ
views/workouts/show_templ.go

This ensures a bug in marshalling, form, etc. can not allow a user to
register directly as an admin, or activate their account during
registration.
Also:
fix(ui): Keep the workout graph at 500px
This keeps the graph at 500px, removing a glitch in the UI on small
screens.
Fixes: #614

fix(user-registration): Make sure user can not register as admin / active

---

frontend/src/views/user/heatmap.js

Added a custom control in leaflet so that user can control the radius and blur in heatmap. Also whether to show markers.
With default settings:
User can change them:

feat: user can control some options in heatmap

---

README.md
docker/docker-compose.base.yaml
docker/docker-compose.dev.postgres.yaml
docker/docker-compose.dev.sqlite.yaml
docker/docker-compose.dev.yaml
docker/docker-compose.postgres.yaml
docker/docker-compose.sqlite.yaml
docker/jwt_encryption_key.txt
pkg/app/app.go
pkg/app/config.go
pkg/database/config.go
workout-tracker.example.yaml

Following conventions to not store secrets in configuration files or
exporting them in environment variables.
See also: https://docs.docker.com/compose/how-tos/use-secrets/
Fixes: #644

feat(secrets): Add support for reading secrets from files

---

pkg/app/workouts.go
pkg/database/workouts.go
views/workouts/details.templ
views/workouts/details_templ.go

Refine manual workout location update logic. Previously, manual workout
locations were only geocoded and updated if the `Address` field was `nil`. This
update now ensures that if a new `Location` string is provided for a manual
workout and it differs from the workout's `FullAddress()`, the location will be
re-geocoded and updated accordingly. This provides more flexible and accurate
manual address updates.
Preserve workout address when locked. When a workout is marked as locked, its
`Address` data is now explicitly preserved when `setData` is called, similar to
how `TotalDistance` and `TotalDuration` are handled. This prevents the address
from being unintentionally overwritten or cleared, ensuring data integrity for
locked workouts.
Display locked status for workout location in UI. The …

feat(location): Improve location handling and display for workouts

---

frontend/lit-localize.json
frontend/src/locale.ts
frontend/xliff/es.xlf
translations/es.yaml
views/helpers/language.go

Add Spanish as a supported localization across the application.
- Enable Spanish in Lit Localize by adding "es" to `lit-localize.json` and updating the dynamic import map in `frontend/src/locale.ts`. This allows the frontend to load and use Spanish translations.
- Introduce `frontend/xliff/es.xlf` which will contain the actual translations for Lit Localize strings, generated by the localization tool.
- Wrap the existing Spanish translations in `translations/es.yaml` under a top-level `es` key. This standardizes the YAML structure to match other language files and improve consistency.
- Register `language.Spanish` in `views/helpers/language.go` to ensure the backend recognizes and supports Spanish for content negotiation and rendering.

feat(i18n): Add Spanish (es) localization

---

pkg/database/workouts.go

When trying to update workouts uploaded with a zip file workout updates are failing because the filename of the individual workouts is the name auf the original zip file causing the worker to use the wrong parser.

fix(workouts) fix workouts uploaded from zip file cannot be updated

---

pkg/converters/fit.go

In fit files the activity field `LocalTimestamp` is not always set (for example Hammerhead Karoo produces such outputs) resulting in workouts getting named e.g. `cycling - 0001-01-01 00:00:00`. 
I added a fallback to the start time of the session.

fix(workout): fix fit file workout name date empty
