jovandeginste/workout-tracker

- assets/output.css
- views/partials/workout_show_stats.html
- views/workouts/workouts_show.html
This is not to save space, but to have a nicer correlation view.
We also move the code forindividual workout statistics to a separate template. This is easier to edit.
> Put the graphs for elevation and speed together

- views/workouts/workouts_add.html
- views/workouts/workouts_edit.html
This got lost when adding the dropdown selection.
This was mentioned in #15.
> Translate the workout types in dropdown selection

- pkg/database/workouts_map.go
Strava appears to export corrected altitude as well
> fix: do not fix altitude for Strava

- pkg/database/workouts_map.go
If we start at 0m elevation, the chance is real this will always be lower than any actual elevation. We now initialize it at 100km, which ... should realistically be higher than any real minimal elevation.
Finally, we will make sure it is not higher than the maxElevation.
> Fix the initial minimum elevation

- pkg/database/workout_type.go
- pkg/database/workouts.go
- translations/de.json
- translations/nl.json
This adds all the workout types that appear in my gpx (not sure if these are standardized, some apps appear to use their own type names...)
> feat: support skiing, snowboarding, kayaking, swimming workouts

- pkg/database/workouts.go
> Remove named return values

- pkg/templatehelpers/icons.go
There is no good icon for kayaking, sadly...
> Add FA icons for the new workout types

- README.md
- pkg/app/config.go
- pkg/app/handlers.go
- pkg/app/users_handlers.go
- views/user/user_login.html
> Add option to disable user registrations

- pkg/database/user.go
> Add details when editing a workout

- pkg/app/api_handlers.go
- pkg/database/statistics.go
- pkg/database/workout_type.go
- pkg/database/workouts_map.go
The new functions let the database do the hard work.
This is the first step; we will convert the existing code to use these new functions.
> Add api endpoints to retrieve statistics, records, etc.

- views/workouts/workouts_edit.html
> Pre-select the current type when editing a workout

- pkg/app/app.go
> Create the profile for the initial admin user

- .github/workflows/docker.yml
> Build Docker image for ARM

- pkg/app/data.go
- pkg/app/templates.go
- views/partials/footer.html
- views/user/user_login.html
- views/workouts/workouts_show.html
- Convert app version to a function in templates
- Add AppConfig as a function and get app settings from there
> Convert data to functions

- pkg/app/api_handlers.go
- pkg/app/routes_test.go
- pkg/database/statistics.go
- pkg/database/user.go
- views/partials/stats_records_totals.html
- views/user/user_show.html
Use the new functions to show the "total" statistics at the top of the dashboard page.
> Show dashboard totals from new functions

- pkg/app/data.go
- pkg/app/handlers.go
- pkg/app/users_handlers.go
- pkg/database/statistics.go
- pkg/database/user_statistics.go
- views/user/user_statistics.html
The data structure in the statistics.go file was updated to no longer add user statistics. The UserStatistics template in the user_statistics.html file was also updated to reflect the changes in the data structure.
The changes ensure that user statistics are retrieved and displayed correctly in the user statistics page.
> Convert user statistics to use the new function

- pkg/app/api_handlers.go
- pkg/database/workouts_statistics.go
- pkg/database/workouts_statistics_test.go
Also add more options for unit breakdown, and improve duration-based breakdown.
> Add API endpoint for single workout statistics (breakdown)

- pkg/app/handlers.go
- pkg/database/statistics.go
- pkg/database/user_statistics.go
- pkg/database/workouts_map.go
- Normalize lat & long degrees before calculating egm96 elevation
- Remove unused code and data
- Add more bucket sizes and report the bucket format in the response
> Several fixups in one PR

- pkg/database/user.go
Since the split of the table with workouts and data, the download no longer worked. This should fix this.
Fixes #93
> Fix download of workouts

- pkg/database/statistics.go
> Calculate average of averages for statistics

- pkg/converters/fit.go
With more samples, we can improve the import logic.
Fixes #106
> Improve support for fit-files

- assets/map.js
- views/partials/workout_show_stats.html
Also show the marker on the map when hovering over the stats.
> Add more information to workout stats

- Makefile
- README.md
- assets/output.css
- pkg/app/self_handlers.go
- pkg/database/gorm_convert.go
- pkg/database/profile.go
- pkg/database/user.go
- translations/de.json
- translations/messages.json
- translations/nl.json
- views/partials/snippet_date.html
- views/partials/workout_details.html
- views/user/user_profile.html
- views/workouts/workouts_list.html
> Add per-user option to display full dates instead of relative dates

- README.md
> Improve docs for Docker, add non-root explanation

- assets/output.css
- package-lock.json
- pkg/database/workouts_map.go
- views/partials/snippet_location.html
- views/partials/workout_details.html
- views/partials/workout_item.html
- views/workouts/workouts_list.html
Some locations are not inside a locality; in this case, we should search for more fields.
Some countries are big enough that a state name should be added too.
Fixes #146
> Check for more location options

- views/partials/workout_details.html
Seems more reasonable to be together.
> Move the time paused together with the total time

- pkg/database/workouts_map.go
Sometimes the geocoding request times out (takes longer than 8 seconds). This change will retry this a number of times, and add a longer delay every time.
> Retry geocoding request to openstreetmap

- translations/it.json
Currently translated at 100.0% (136 of 136 strings)
Translation: Workout Tracker/Web interface
Translate-URL: https://hosted.weblate.org/projects/workout-tracker/web-interface/it/
> Translated using Weblate (Italian)

- pkg/database/workout_type.go
- pkg/templatehelpers/icons.go
- views/partials/messages.html
Improve the visuals of the newly added test-workouts (push-ups, weight lifting)
> Add weight-based workout icons

- Makefile
- README.md
- assets/output.css
- main.css
- package-lock.json
- package.json
- views/equipment/equipment_list.html
- views/workouts/workouts_list.html
This renders the workouts and equipments tables unsortable (for now).
> Remove dependency on sorttable

- assets/output.css
- main.css
- pkg/app/handlers.go
- pkg/app/routes.go
- pkg/app/workouts.go
- pkg/database/workouts.go
- pkg/database/workouts_map.go
- pkg/geocoder/reverse.go
- views/address_results.html
- views/partials/workout_details.html
- views/partials/workout_item.html
- views/partials/workouts_list_details.html
- views/workouts/workout_form.html
This will perform a lookup of the location when the user types a partial location, and give suggestions to the user. The user can then click any suggestion to use it.
> Improve input of location for manual workouts

- pkg/app/workouts.go
- pkg/geocoder/reverse.go
Only set the full address if it matches exactly. Otherwise use whatever the user typed as the location.
> Allow partial location

- CHANGELOG.md
- assets/output.css
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- main.css
- pkg/app/app.go
- pkg/app/routes.go
- pkg/app/self_handlers.go
- pkg/database/config.go
- pkg/database/user.go
- views/partials/footer.html
- views/partials/head.html
- views/partials/header.html
- views/partials/version.html
- views/user/version_updated.html
- views/workouts/workouts_add.html
- views/workouts/workouts_edit.html
Keep track of what version each user last used and show a banner when an update was done.
> Show a message per user when the application was updated

- pkg/app/equipment_handlers.go
> fix: update default workout types when editing equipment

- Makefile
- pkg/app/i18n.go
- translations/id.json
- vendor/github.com/vorlif/spreak/humanize/locale/id/django.po
- vendor/github.com/vorlif/spreak/humanize/locale/id/locale.go
- vendor/modules.txt
Empty for now, waiting for community to translate.
> feat: add Indonesian language

- assets/output.css
- main.css
- pkg/app/admin_handlers.go
- pkg/app/workouts_handlers.go
- pkg/converters/fit.go
- pkg/database/workout_type.go
- pkg/database/workouts.go
- views/partials/snippet_date.html
- views/partials/stats_records_distance.html
- views/partials/workout_details.html
- views/partials/workout_item.html
- views/partials/workouts_list_details.html
- views/workouts/workouts_list.html
This show the tempo (km/min) instead of the speed (km/h) when the workout type is running. It keeps track of imperial units too.
Supercedes #251
> Show tempo for running (speed for others)

- .golangci.yml
- pkg/app/admin_data.go
- pkg/app/alerts.go
- pkg/app/api_handlers.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/data.go
- pkg/app/i18n.go
- pkg/app/routes_test.go
- pkg/app/templates.go
- pkg/converters/fit.go
- pkg/converters/tcx.go
- pkg/database/gpx_sample_1_test.go
- pkg/database/user_test.go
- pkg/database/workouts.go
- pkg/database/workouts_statistics.go
- pkg/database/workouts_test.go
- pkg/geocoder/reverse.go
- pkg/templatehelpers/icons.go
- pkg/templatehelpers/template_funcs.go
Add a `.golangci.yml` file to configure golangci-lint.
This will help us find and fix common errors and code style issues early on, leading to better code quality and maintainability.
> feat: add golangci-lint configuration

- assets/output.css
- main.css
- views/partials/workout_item.html
- views/partials/workouts_list_details.html
- views/user/user_show.html
This removes the (duplicate) location fro the dashboard tiles. We also make sure long elements (such as locations) are ellipsized.
Fixes #257
> Remove location from dashboard tiles, cosmetic improvements

- .prettierignore
- .prettierrc.json
- CHANGELOG.md
- README.md
- Adds a .prettierrc.json file to configure prettier.
- Adds the proseWrap option to .prettierrc.json to force line breaks in long strings to make the code and documentation more readable.
> feat: add prettier configuration

- pkg/app/i18n.go
- translations/fa.json
- vendor/github.com/vorlif/spreak/humanize/locale/fa/django.po
- vendor/github.com/vorlif/spreak/humanize/locale/fa/locale.go
- vendor/modules.txt
Adds support for the Persian language (fa).
> feat: add Persian language support

- README.md
Add a Matrix chat badge to the README.md to make it easier for users to connect with the project community.
> feat: Add Matrix chat badge

- pkg/app/workouts_handlers.go
- pkg/database/route_segments.go
- pkg/database/user.go
- pkg/database/workouts.go
- pkg/database/workouts_map.go
- views/workouts/workouts_list.html
> feat: Delay expensive workout actions to background routine

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- pkg/app/api_handlers.go
Hi fix swagger documentation in code because of wrong usage of Param
those two Param missus in swagger that in result `make swagger` field
if you think those two parameter not be optional change them to true.
later i should to review that and add swagger check to CI too.
> fix: wrong usage of Param for swagger

- pkg/templatehelpers/icons.go
it is related to #284 
later i will review that code to make that better but for now try to fix golangci-lint error that remain in code 
Note: why i don't use single map? i am not complety read the code right now but if should search in maps multiple time maybe smaller map be better instead of load the full map each time . beside ram usage it can affect search time in map (i will review that later and try to find a better solution for that)
> use map for icons

- pkg/app/i18n.go
- translations/ru.json
- vendor/github.com/vorlif/spreak/humanize/locale/ru/django.po
- vendor/github.com/vorlif/spreak/humanize/locale/ru/locale.go
- vendor/modules.txt
Add support for the Russian language.
> feat: Add Russian translation

- pkg/database/workouts.go
- views/partials/workout_details.html
- views/partials/workout_map.html
- views/partials/workout_social.html
- views/partials/workouts_list_details.html
- views/workouts/workouts_route_segment.html
- views/workouts/workouts_show.html
This prevents issues when the data is nil.
> Dispatch all data functions used in the views

- go.mod
- go.sum
- pkg/converters/tcx.go
- vendor/github.com/galeone/tcx/tcxschema.go
- vendor/github.com/galeone/tcx/unmarshal.go
- vendor/modules.txt
The update improves the handling of heart rate and cadence data within the GPX conversion.
Fixes #318
> chore(deps): update github.com/galeone/tcx

- pkg/app/api_handlers.go
> Fix the user lookup function for API calls

- assets/output.css
- pkg/app/i18n.go
- pkg/app/users_handlers.go
- pkg/database/profile.go
- tailwind.config.js
- views/partials/head.html
- views/partials/theme.html
- views/user/user_profile.html
> Add profile option to switch app theme

- pkg/app/templates.go
- views/partials/workout_show_stats.html
> Fix timezone issues in workout statistics

- pkg/app/workouts_filter.go
- views/workouts/workouts_list.html
Improved the UI by using a details element to collapse the filter form. This keeps the UI cleaner and less cluttered by default, whilst maintaining the accessibility of the filters. Added default values to the filter form for a better user experience.
> feat(filter): Improved filter UI

- Makefile
- assets/output.css
- package-lock.json
- package.json
- pkg/app/handlers.go
- pkg/app/routes.go
- pkg/templatehelpers/icons.go
- views/partials/header.html
- views/user/heatmap.html
This adds a new summary page, with a world map showing the heat map of your workouts.
Fixes #335
> Add heat map of workouts

- Makefile
- assets/output.css
- package-lock.json
- package.json
- pkg/app/api_handlers.go
- pkg/app/data.go
- views/user/heatmap.html
This shows a more detailed heat map, where every single coordinate is drawn (instead of only the workout centers)
> Draw all coordinates individually

- assets/output.css
- pkg/app/workouts.go
- pkg/database/gorm.go
- pkg/database/workouts.go
- pkg/database/workouts_map.go
- pkg/templatehelpers/icons.go
- views/partials/workout_details.html
- views/workouts/workout_form.html
- add timezone support to manual workout creation
- collect extra metrics as separate field for quick lookups
- hide information without content (eg. elevation, when everything is 0)
- add accuracy as an extra metric
> A bundle of fixes

- assets/output.css
- main.css
Improved the color contrast of the version notice, notice, and alert elements for better readability in light mode.
> Style(css): Update notice colors

- assets/output.css
- pkg/app/api_handlers.go
- pkg/app/data.go
- pkg/app/routes.go
- pkg/app/templates.go
- pkg/templatehelpers/icons.go
- views/user/heatmap.html
- views/workouts/workout_details.html
- Fix the user auth flow for API endpoints
- Improve the workout tooltip on the heatmap
- Style(css): Increase default heatmap height
- fix(app): Correctly return error when parsing view templates
> A number of fixes

- views/workouts/list_details.templ
- views/workouts/list_details_templ.go
> Always show workout details in lists

- views/equipment/show.templ
- views/equipment/show_templ.go
- views/route_segments/details.templ
- views/route_segments/details_templ.go
- views/route_segments/edit.templ
- views/route_segments/edit_templ.go
- views/route_segments/list.templ
- views/route_segments/list_templ.go
- views/route_segments/show.templ
- views/route_segments/show_templ.go
- views/workouts/create_route_segment.templ
- views/workouts/create_route_segment_templ.go
- views/workouts/details.templ
- views/workouts/details_templ.go
- views/workouts/edit.templ
- views/workouts/edit_templ.go
- views/workouts/item.templ
- views/workouts/item_templ.go
- views/workouts/list.templ
- views/workouts/list_templ.go
- views/workouts/route_segments.templ
- views/workouts/route_segments_templ.go
- views/workouts/show.templ
- views/workouts/show_templ.go
The name display of workouts and route segments has been improved to handle long names and empty names more gracefully. A new helper function `Name` was added to handle this consistently across the application.
Fixes #388
> Refactor(views): Improve workout and route segment name display

- pkg/database/route_segment_matching.go
- pkg/database/route_segment_test.go
- pkg/database/segment1_test.go
- pkg/database/segment2_test.go
- pkg/database/track_test.go
- views/route_segments/add.templ
- views/route_segments/add_templ.go
- views/route_segments/list.templ
- views/route_segments/list_templ.go
> Add route segment tests

- translations/fi.yaml
- views/helpers/language.go
- views/partials/partials.templ
- views/partials/partials_templ.go
- views/user/profile_preferred_units.templ
- views/user/profile_preferred_units_templ.go
> Finnish translations

- assets/output.css
- pkg/database/workouts_filter.go
Instead of "all", we now use "forever"; this change was not done
everywhere, which lead to inconsistencies.
> fix(filter): Update the unscoped value for the `since` filter

- pkg/converters/ftb.go
- pkg/converters/parse.go
- pkg/converters/zip.go
This will unpack zip files and parse each file inside separately.
> feat(zip): Add support for zip files

- views/workouts/add.templ
- views/workouts/add_templ.go
This commit introduces support for uploading zip and ftb files for workouts.
> feat(workouts): Allow uploading zip and ftb files

- translations/en.yaml
- views/workouts/add.templ
- views/workouts/add_templ.go
Add a number of online resources with tools to edit or convert your GPX file before uploading.
Ref: #329, #399
> chore(docs): Add resources to edit GPX files

- CHANGELOG.md
- translations/pl.yaml
> feat(i18n): Enable Polish translation

- pkg/app/admin_data.go
- pkg/app/api_handlers.go
- pkg/app/background.go
- pkg/app/data.go
- pkg/app/equipment_handlers.go
- pkg/app/route_segments_handlers.go
- pkg/app/workouts_handlers.go
- pkg/database/equipment.go
- pkg/database/gorm.go
- pkg/database/route_segments.go
- pkg/database/user.go
- pkg/database/user_test.go
- views/workouts/form.templ
- views/workouts/form_templ.go
It is currently not possible to edit workout equipment. 
resolves part of #507
> Fix workout equipment not saved

- pkg/database/statistics.go
- views/helpers/helpers.go
- views/helpers/statistics.go
- views/user/statistics.templ
- views/user/statistics_templ.go
- views/workouts/list.templ
- views/workouts/list_templ.go
> fix(filters): Fix the different filters with translation keys

- pkg/geocoder/reverse.go
This commit introduces the SearchLocations function, which exposes the internal search function. This allows external packages to leverage the geocoder's search functionality directly.
> feat: expose SearchLocations function

- translations/en.yaml
- views/route_segments/edit.templ
> fix(translation): Fix translation of update button for route route_segments

- views/user/show.templ
The others users section should be displayed only if we have more than the main user.
> fix(ui): change the test on other users sections

- pkg/converters/workout.go
- pkg/database/workouts.go
- pkg/templatehelpers/template_funcs.go
- translations/en.yaml
- views/helpers/humanize.go
- views/workouts/details.templ
- views/workouts/details_templ.go
Also adds a new icon to extra metrics if speed is available.
> Add cadence stats to workout details

- frontend/src/views/workouts/show_stats.js
- views/workouts/show.templ
- views/workouts/show_stats.templ
- views/workouts/show_stats_templ.go
- views/workouts/show_templ.go
* display all trackpoints instead of 1 min intervals
* add temperature readings
* prefer speed readings from extra metric
* hide metrics that are not available
* refactoring
Preferred unit for temperature readings still need to be added.
> feat(workout) improve workout detail chart

- frontend/src/main.css
- frontend/src/views/user/heatmap.js
follow up of https://github.com/jovandeginste/workout-tracker/pull/623
I also added a behavior that disables these two range inputs when onlyTrace checkbox is checked. However, the hover highlight for input elements will cause disabled range input look strange. So I excluded range input in main.css.
> fix: heatmap config text in dark mode

- .github/workflows/test.yml
Adds a check to the test workflow that checks if the generated go files from templ are in sync with the templ files.
> Add generated templ files check to test workflow

- frontend/src/components/map.js
- pkg/app/background.go
- pkg/database/workouts_map.go
- pkg/database/workouts_slope.go
- translations/de.yaml
- translations/en.yaml
- translations/fr.yaml
- translations/nl.yaml
- views/workouts/data-json.templ
- views/workouts/data-json_templ.go
- views/workouts/show.templ
- views/workouts/show_templ.go
> Improve slope detection

- pkg/geocoder/reverse.go
Externalize geocoder client configuration constants
Move `OSMURL`, `RetryMax`, `RetryWaitMin`, `ClientTimeout`, and
`RequestInterval` to package-level exported variables. This allows external
configuration and customization of the geocoder client's behavior, improving
flexibility and testability.
Introduce `ResetClient` and make `SetClient` idempotent
Add a new `ResetClient` function to allow explicit re-initialization or
reconfiguration of the geocoder client. The existing `SetClient` function is
modified to only initialize the client if it hasn't been set yet, ensuring that
initial setup is performed only once for safety, while `ResetClient` provides a
way to force a refresh.
Integrate `slog.Logger` with `retryablehttp.Client`
Pass the provided `slog.Logger` to the underlying …
> refactor(geocoder): Externalize client config and improve initialization

- frontend/src/views/workouts/breakdown.ts
- frontend/src/views/workouts/show_stats.ts
- frontend/xliff/de.xlf
- frontend/xliff/fa.xlf
- frontend/xliff/fi.xlf
- frontend/xliff/fr.xlf
- frontend/xliff/it.xlf
- frontend/xliff/nb-NO.xlf
- frontend/xliff/nl.xlf
- frontend/xliff/pl.xlf
- frontend/xliff/pt-BR.xlf
- frontend/xliff/ru.xlf
- frontend/xliff/tr.xlf
- frontend/xliff/zh-Hans.xlf
- translations/en.yaml
- translations/nl.yaml
- views/workouts/show.templ
- views/workouts/show_stats.templ
- views/workouts/show_stats_templ.go
- views/workouts/show_templ.go
part of #620 
Adds the option to switch the x-axis of the workout chart between time and distance.
> feat(workout) Add workout chart distance x-axis

- pkg/database/workouts_slope.go
Follow up to #675. 
Currently the slope values include outliers (at least on my data) which make it impossible to read max/min values. This adds a more sophisticated algorithm to calculate slope. 
It uses a weighted average at each point and requires points to be at least 20m apart. 
I only did minor testing on this but on first sight it seems to perform okay. However it seems that this approach has a slight tendency to underestimate values. Maybe changing the window size and min dist could improve that.
> feat(workout) smooth slope values to filter outliers

- README.md
- docker/docker-compose.yaml
- pkg/app/background.go
- pkg/app/config.go
- pkg/database/config.go
Allow different worker delays, eg. for dev. Also clean up some (new) linting
issues.
> feat(worker): Allow custom worker delay time
